// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testsuite.proxies;

public class Node extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSuite.Node";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		number("number"),
		_id("_id"),
		group("group"),
		relation("relation"),
		jobtitle("jobtitle"),
		address("address"),
		contact("contact"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Node_Nodes("TestSuite.Node_Nodes");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Node(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSuite.Node"));
	}

	protected Node(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject)
	{
		super(context, nodeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TestSuite.Node", nodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSuite.Node");
	}

	/**
	 * @deprecated Use 'Node.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testsuite.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testsuite.proxies.Node.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testsuite.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testsuite.proxies.Node(context, mendixObject);
	}

	public static testsuite.proxies.Node load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testsuite.proxies.Node.initialize(context, mendixObject);
	}

	public static java.util.List<testsuite.proxies.Node> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testsuite.proxies.Node> result = new java.util.ArrayList<testsuite.proxies.Node>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSuite.Node" + xpathConstraint))
			result.add(testsuite.proxies.Node.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of number
	 */
	public final java.lang.String getnumber()
	{
		return getnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of number
	 */
	public final java.lang.String getnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.number.toString());
	}

	/**
	 * Set value of number
	 * @param number
	 */
	public final void setnumber(java.lang.String number)
	{
		setnumber(getContext(), number);
	}

	/**
	 * Set value of number
	 * @param context
	 * @param number
	 */
	public final void setnumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String number)
	{
		getMendixObject().setValue(context, MemberNames.number.toString(), number);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of group
	 */
	public final java.lang.String getgroup()
	{
		return getgroup(getContext());
	}

	/**
	 * @param context
	 * @return value of group
	 */
	public final java.lang.String getgroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.group.toString());
	}

	/**
	 * Set value of group
	 * @param group
	 */
	public final void setgroup(java.lang.String group)
	{
		setgroup(getContext(), group);
	}

	/**
	 * Set value of group
	 * @param context
	 * @param group
	 */
	public final void setgroup(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String group)
	{
		getMendixObject().setValue(context, MemberNames.group.toString(), group);
	}

	/**
	 * @return value of relation
	 */
	public final java.lang.String getrelation()
	{
		return getrelation(getContext());
	}

	/**
	 * @param context
	 * @return value of relation
	 */
	public final java.lang.String getrelation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.relation.toString());
	}

	/**
	 * Set value of relation
	 * @param relation
	 */
	public final void setrelation(java.lang.String relation)
	{
		setrelation(getContext(), relation);
	}

	/**
	 * Set value of relation
	 * @param context
	 * @param relation
	 */
	public final void setrelation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relation)
	{
		getMendixObject().setValue(context, MemberNames.relation.toString(), relation);
	}

	/**
	 * @return value of jobtitle
	 */
	public final java.lang.String getjobtitle()
	{
		return getjobtitle(getContext());
	}

	/**
	 * @param context
	 * @return value of jobtitle
	 */
	public final java.lang.String getjobtitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.jobtitle.toString());
	}

	/**
	 * Set value of jobtitle
	 * @param jobtitle
	 */
	public final void setjobtitle(java.lang.String jobtitle)
	{
		setjobtitle(getContext(), jobtitle);
	}

	/**
	 * Set value of jobtitle
	 * @param context
	 * @param jobtitle
	 */
	public final void setjobtitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jobtitle)
	{
		getMendixObject().setValue(context, MemberNames.jobtitle.toString(), jobtitle);
	}

	/**
	 * @return value of address
	 */
	public final java.lang.String getaddress()
	{
		return getaddress(getContext());
	}

	/**
	 * @param context
	 * @return value of address
	 */
	public final java.lang.String getaddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.address.toString());
	}

	/**
	 * Set value of address
	 * @param address
	 */
	public final void setaddress(java.lang.String address)
	{
		setaddress(getContext(), address);
	}

	/**
	 * Set value of address
	 * @param context
	 * @param address
	 */
	public final void setaddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.address.toString(), address);
	}

	/**
	 * @return value of contact
	 */
	public final java.lang.String getcontact()
	{
		return getcontact(getContext());
	}

	/**
	 * @param context
	 * @return value of contact
	 */
	public final java.lang.String getcontact(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.contact.toString());
	}

	/**
	 * Set value of contact
	 * @param contact
	 */
	public final void setcontact(java.lang.String contact)
	{
		setcontact(getContext(), contact);
	}

	/**
	 * Set value of contact
	 * @param context
	 * @param contact
	 */
	public final void setcontact(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contact)
	{
		getMendixObject().setValue(context, MemberNames.contact.toString(), contact);
	}

	/**
	 * @return value of Node_Nodes
	 */
	public final testsuite.proxies.Nodes getNode_Nodes() throws com.mendix.core.CoreException
	{
		return getNode_Nodes(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_Nodes
	 */
	public final testsuite.proxies.Nodes getNode_Nodes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testsuite.proxies.Nodes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Node_Nodes.toString());
		if (identifier != null)
			result = testsuite.proxies.Nodes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Node_Nodes
	 * @param node_nodes
	 */
	public final void setNode_Nodes(testsuite.proxies.Nodes node_nodes)
	{
		setNode_Nodes(getContext(), node_nodes);
	}

	/**
	 * Set value of Node_Nodes
	 * @param context
	 * @param node_nodes
	 */
	public final void setNode_Nodes(com.mendix.systemwideinterfaces.core.IContext context, testsuite.proxies.Nodes node_nodes)
	{
		if (node_nodes == null)
			getMendixObject().setValue(context, MemberNames.Node_Nodes.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Node_Nodes.toString(), node_nodes.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testsuite.proxies.Node that = (testsuite.proxies.Node) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSuite.Node";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
