// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package d3.proxies;

public class Items
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "D3.Items";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Item_JsonObject("D3.Item_JsonObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Items(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "D3.Items"));
	}

	protected Items(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemsMendixObject)
	{
		if (itemsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("D3.Items", itemsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a D3.Items");

		this.itemsMendixObject = itemsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Items.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static d3.proxies.Items initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return d3.proxies.Items.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static d3.proxies.Items initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new d3.proxies.Items(context, mendixObject);
	}

	public static d3.proxies.Items load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return d3.proxies.Items.initialize(context, mendixObject);
	}

	public static java.util.List<d3.proxies.Items> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<d3.proxies.Items> result = new java.util.ArrayList<d3.proxies.Items>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//D3.Items" + xpathConstraint))
			result.add(d3.proxies.Items.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Item_JsonObject
	 */
	public final d3.proxies.Country getItem_JsonObject() throws com.mendix.core.CoreException
	{
		return getItem_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Item_JsonObject
	 */
	public final d3.proxies.Country getItem_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		d3.proxies.Country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Item_JsonObject.toString());
		if (identifier != null)
			result = d3.proxies.Country.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Item_JsonObject
	 * @param item_jsonobject
	 */
	public final void setItem_JsonObject(d3.proxies.Country item_jsonobject)
	{
		setItem_JsonObject(getContext(), item_jsonobject);
	}

	/**
	 * Set value of Item_JsonObject
	 * @param context
	 * @param item_jsonobject
	 */
	public final void setItem_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, d3.proxies.Country item_jsonobject)
	{
		if (item_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Item_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Item_JsonObject.toString(), item_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final d3.proxies.Items that = (d3.proxies.Items) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "D3.Items";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
